spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/pizzariaNicolas?createDatabaseIfNotExist=true
        username: root
        password: Janete10!

jpa:
    show-sql: true

server:
    error:
        include-stacktrace: never